stages:
  train:
    cmd: python train.py
    deps:
    - data/iris.csv
    - train.py
    metrics:
    - metrics.json:
        cache: false
    params:
    - train.n_estimators
    - train.random_state
    - train.test_size
    outs:
    - model.pkl
